syncs:
  - repos:
      - hostlikepro/debian_server
      - hostlikepro/.github-private
      - hostlikepro/images
      - hostlikepro/hostlike.pro
    files:
      - src: workflows/labels.yml
        dest: .github/labels.yml
      - src: test.txt
        dest: text.txt