name: Settings Repo Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            hostlikepro/.github-private@main
            hostlikepro/images@main
            hostlikepro/hostlike.pro@main
            hostlikepro/debian_server@main
          FILES: |
            .github/labels.yml=.github/labels.yml
            .github/workflows/add-to-designers.yml=.github/workflows/add-to-designers.yml
            .github/workflows/add-to-general.yml=.github/workflows/add-to-general.yml
            .github/workflows/add-to-smm.yml=.github/workflows/add-to-smm.yml
          TOKEN: ${{ secrets.SYNC_TOKEN }}